# Generated by Django 5.0.2 on 2024-04-05 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('icone', models.URLField(max_length=1000)),
                ('rank', models.IntegerField()),
                ('descricao', models.TextField()),
                ('data_lancamento', models.DateField()),
                ('nota', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('link', models.URLField(max_length=1000)),
                ('tipo', models.CharField(choices=[('pg', 'Pagina do jogo'), ('wk', 'Wiki do Jogo'), ('vi', 'Video do jogo'), ('jo', 'Jogo na internet'), ('ou', 'Outros')], max_length=2)),
                ('favorito', models.BooleanField()),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meusJogosFavoritos.jogo')),
            ],
        ),
    ]
